"""Prepend an auto-generated "generated by" info panel to the page body.

``options.generated_by`` follows the :class:`SyncContext` convention: ``None``
means use the default notice, an empty/blank string suppresses the panel, and
any other string is a template that may contain ``%{filepath}``,
``%{filename}``, ``%{filedir}`` and ``%{filestem}`` placeholders.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from lxml import etree

from sync_confluence.converter._csf import AC, ElementType, qname
from sync_confluence.converter._result import ConverterOptions, SourcePaths

DEFAULT_GENERATED_BY = "This page is auto-generated. Do not edit directly."


def apply_generated_by_template(template: str, relative_path: Path) -> str:
    """Substitute the ``%{...}`` path placeholders in *template*."""
    return (
        template.replace("%{filepath}", relative_path.as_posix())
        .replace("%{filename}", relative_path.name)
        .replace("%{filedir}", relative_path.parent.as_posix())
        .replace("%{filestem}", relative_path.stem)
    )


def _relative_path(paths: SourcePaths) -> Optional[Path]:
    if paths.current_file is None:
        return None
    if paths.docs_root is not None:
        try:
            return paths.current_file.relative_to(paths.docs_root)
        except ValueError:
            return Path(paths.current_file.name)
    return Path(paths.current_file.name)


def _info_panel(text: str) -> ElementType:
    paragraph = etree.Element("p")
    paragraph.text = text
    body = AC("rich-text-body")
    body.append(paragraph)
    macro = AC("structured-macro", {qname("ac", "name"): "info"})
    macro.append(body)
    return macro


def prepend_generated_by(root: ElementType, options: ConverterOptions) -> None:
    """Insert the generated-by info panel as the first child of *root*."""
    raw = options.generated_by
    if raw is not None and not raw.strip():
        return
    template = DEFAULT_GENERATED_BY if raw is None else raw
    relative = _relative_path(options.paths)
    text = apply_generated_by_template(template, relative) if relative else template
    root.insert(0, _info_panel(text))
