name: Build otel-log-wrapper


on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: |
        cd otel-log-wrapper
        python -m build

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./otel-log-wrapper/dist/*