name: Build otel_log_wrapper

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  validate:
    name: Validate otel_log_wrapper package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Validate package
      uses: ./.github/actions/validate-package
      with:
        package-dir: otel_log_wrapper
        python-version: '3.x'

  deploy:
    name: Build and release otel_log_wrapper package
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Build package
      uses: ./.github/actions/build-and-release
      with:
        package-dir: otel_log_wrapper
        python-version: '3.x'

    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        files: ./otel_log_wrapper/dist/*
